### PR TITLE
Fixes for Julia 0.7

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by samoconnor** [comment]
Thanks for this @ararslan.
I'd prefer this PR to not use Compat and drop Julia 0.6 support.
I would really like to try to avoid breaking any existing Julia 0.6 AWSCore based production code by introducing a subtle bug in the process of 0.7 updates.

**Comment by ararslan** [comment]
I've removed Compat and set the minimum version to 0.7.

**Comment by ararslan** [comment]
Thanks! Could I trouble you for a tag here too? :grin:

**Comment by samoconnor** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/16029

**Pull request merged**
